/* eslint-disable no-unused-vars */
import { Flex, Input, Text, useTheme } from '@chakra-ui/react';
import {
  ApiOutlined,
  AvTimerOutlined,
  DoDisturbAltOutlined,
  FilterAltOutlined,
  FormatOverlineOutlined,
  SearchOutlined,
  SubdirectoryArrowRightOutlined,
  SyncAltOutlined,
  TroubleshootOutlined,
  TuneOutlined
} from '@mui/icons-material';

import React, { useState } from 'react';
const products = [
  'milkmade',
  '200ml',
  'tata gold',
  'jivo',
  'samyang',
  'cave man',
  'morton',
  'five star',
  '6kg',
  'la folie',
  'elina',
  'nutrifud',
  'snapin',
  'winkies',
  'vio',
  'vi-john',
  'nova',
  '&',
  'tez',
  'iddla',
  'mafix',
  'lion',
  '1',
  'heinz',
  'kraft',
  '2',
  '3',
  '4',
  'dairy power',
  '5',
  '6',
  '7',
  '8',
  '9',
  'tata agni',
  'gulab',
  'baskin robins',
  'ribbons and balloons',
  'nail trend',
  'hb bakers choice',
  'devaaya',
  'karachi',
  'kit kat',
  'nutella',
  'kinder joy',
  'kaccha mango',
  "amma's",
  "sid's farm",
  'oven supreme',
  'g',
  'derista',
  'idhayam',
  'coloressence',
  'the',
  'Sid Farm',
  'baker street',
  'britannia',
  'wai wai',
  'sri sri tattva',
  "elpee'z",
  'sarvottam',
  'pravin',
  '4kg',
  'godrej',
  'shree',
  'navratna',
  'kapiva',
  'kaffe',
  'levista',
  'inchi',
  "kwality wall's",
  'sumul',
  'parle agro',
  'tetley',
  'nestle',
  '300ml',
  'vaseline',
  'kalpasree',
  "lil'goodness",
  'soulfull',
  'lindt',
  'double hiran',
  'crax',
  'lavian',
  'daawat',
  'society',
  'engine',
  'grb',
  'dairy pure',
  'aadhar',
  'dairy life',
  'nafees',
  'bullet',
  'fresca',
  'ziggy',
  'dutchie',
  'vijaya',
  'bikaji',
  'Bambooz',
  'center fresh',
  'landana',
  'leonardo',
  'keventer',
  'moreish',
  'lotus biscoff',
  'stella',
  'weikfield',
  'london dairy',
  'amrit',
  'veeba',
  'naman',
  'sanchi',
  'sapins',
  '2kg',
  'yummiez',
  'veg affaire',
  'uncle chipps',
  'pass pass',
  'osam',
  'varalakshmi',
  'litre',
  'arata',
  '400',
  'jiomart',
  'hathi',
  'lafz',
  'vezlay',
  'hamdard',
  'happilo',
  'presto',
  'aakash',
  'milky moo',
  'country harvest',
  'minute maid',
  'vinvik',
  'arla',
  'dabur',
  'wyke farms',
  'taj mahal',
  'parle nutricrunch',
  '650',
  'mori-nu',
  'milkfood',
  'moowing',
  'pmark',
  'product',
  'asian',
  'jubilee',
  'parampara',
  'wagh bakri',
  'kingfisher',
  'home spring',
  'vandevi',
  'bhagirathi',
  'shan',
  'sri sri',
  'gold winner',
  'ford farm',
  'rro dairy',
  'bauli',
  'krackjack',
  "baker's choice",
  'aeroplane',
  'threptin',
  'farmley',
  'ice cream',
  'saras',
  'thirumala',
  'namaste india',
  '100ml',
  'gowardhan',
  'badshah',
  'dukes',
  'swadist',
  'below',
  'kings',
  'crave',
  'bisleri',
  'real',
  'bail kolhu',
  'nice time',
  'swad',
  '200',
  'puff master',
  'apis',
  'nasta',
  'amulya',
  'bingo',
  'imagine meats',
  'sorrentina',
  'schweppes',
  'jivana',
  'provedic',
  'jivraj 9',
  'al forno',
  'jalani',
  'smoodh',
  'shakti',
  'park avenue',
  'eva',
  'cremberie',
  'emami',
  'MotherDairy',
  'gaay chhap',
  'pride of cows',
  'hello life',
  'sarda farms',
  'sunfeast caker',
  'medha',
  'bakewell',
  'britannia treat',
  'ltrs',
  'ruchi',
  'naga',
  'free range',
  'vaidyam',
  'dairy craft',
  'castello',
  'nic',
  '500g',
  'budweiser',
  'dinshaw',
  'pillsbury',
  'spice temptation',
  'farmtodine',
  'leo',
  'thums up',
  "shalimar's",
  'zandu',
  'nabati',
  'samrat',
  'anik',
  'happy milk',
  'saiaamrut',
  'madhur',
  'disano',
  'anmol',
  'korndrop',
  'whiskas',
  'anil',
  'peppy',
  'marino',
  'sunrise',
  'foodstrong juniors',
  '250',
  'cardia',
  '500ml',
  'appy',
  'tata premium',
  'prasuma',
  'red label',
  'popular',
  'himalaya',
  'kwality',
  "ammamma's",
  'priyagold',
  'sheba',
  'lotus make-up',
  'mamy poko',
  'vadilal',
  'nissin',
  '250ml',
  'sunfeast',
  'sunkots',
  'dodoni',
  'english bake',
  'aavin',
  'bambino',
  'govind',
  'parivar',
  'hersheys',
  'pediasure',
  'girnar',
  'Celebration Essentials',
  'vachan',
  'nutralite',
  'manna',
  'gaay',
  'eastern',
  'rasna',
  'grameen',
  'Mother Dairy',
  "dinshaw's",
  'del monte',
  'delicious',
  'mariegold',
  'mapro',
  'surabhi',
  'omved',
  'biotique',
  'sivaji',
  'sakthi',
  'ras luxury oils',
  'ksheer',
  'gits',
  'akshayakalpa',
  'kots',
  'tulips',
  'dreamery',
  'guruji',
  '500 gm',
  'perk',
  'avt',
  'umang',
  'harvest',
  'bonn',
  'good life',
  'riso',
  'marvel',
  'britannia the laughing cow',
  'superfit',
  'pushp',
  'horlicks',
  'borges',
  'dhara',
  'sri murugan',
  'the brooklyn creamery',
  'jalan',
  'happy',
  'parsi dairy',
  'srikrishna',
  'Freshwrapp',
  'american bakers',
  'bare essentials',
  'catch',
  'muralya',
  '400ml',
  'modern dairies',
  'durga',
  'good morning',
  'ruchi gold',
  'farm fresh',
  'heritage',
  'britannia dairy',
  'sunday',
  'metro',
  'mccain',
  'punjab sind',
  'starbuck',
  'granarolo',
  'cornitos',
  'sagar',
  'himalayan',
  'nutoras',
  'swastik',
  'organic tattva',
  'shreeja',
  'bournville',
  'cothas',
  'elite',
  'sona sikka',
  'kilo',
  'freedom',
  '9kg',
  'mountain dew',
  'mashal',
  'saboro',
  'scooter',
  'richcups',
  'sunland',
  'nature fresh',
  'bikano',
  "collier's",
  'mcvities',
  'pitambari',
  'india gate',
  'fiona',
  'brahmins',
  'vimal',
  'paayas',
  'mr gold',
  'kanan devan',
  'kwality walls',
  '400 ml',
  'lays',
  'english oven',
  'pilsburry',
  'tilsona',
  'kanodia',
  'alpino',
  'dermafique',
  'soopers bytes',
  'raja',
  'dr rhazes',
  'kabhi b',
  '500gm',
  'alpenliebe',
  'pansari',
  'moti',
  'king',
  'liter',
  'ajmi',
  'bolas',
  'sunfeast farmlite',
  'just breads',
  'sonai',
  'udhaya krishna',
  'sugar',
  'only earth',
  'top n town',
  'healthy heart',
  'doritos',
  'laxminarayan',
  'aadya',
  'pure magic',
  'kriti',
  'the laughing cow',
  '7kg',
  'baidyanath',
  'bevzilla',
  'nirma',
  'figaro',
  'godrej jersey',
  'iceland',
  'ltr',
  'asal',
  'aarambh',
  'vega',
  'laxmi bhog',
  'hangyo',
  'guinea',
  'saloni',
  'ripuraj',
  'tata tea',
  'Ezee',
  'westminster',
  'delmonte',
  'rani',
  'mahesh',
  "haldiram's",
  'chuk de',
  '3 roses',
  'mogu mogu',
  'emporio',
  'malkist',
  'bounty',
  'alpen',
  'krafts',
  'monte carlo',
  'melt in',
  'pintola',
  'colavita',
  'diva',
  'geeta',
  'atmasantosh',
  'davidoff',
  "johnson's baby",
  'whisper',
  'miss claire',
  '3',
  '10',
  '102',
  'jelly',
  '10kg',
  'sumeru',
  '12',
  '123',
  'akfe',
  'bas',
  'basundi',
  'bavarian',
  'dlecta',
  'diva professional',
  'econa',
  'hemi wala',
  'jerk',
  'le freshe',
  'lucas',
  'milk',
  'octavius',
  'paradise',
  'rokado',
  'shazi',
  'sta',
  'stoney brook',
  'tata sampann',
  'til'
];

const ConfigSearchBar = ({ input, setInput, onSubmit, placeholder }) => {
  const theme = useTheme();

  return (
    <Input
      _focus={{
        backgroundColor: `${theme.colors.tertiary.hover} !important`
      }}
      _hover={{
        backgroundColor: `${theme.colors.tertiary.background} !important`
      }}
      bg={theme.colors.tertiary.background}
      border={`1px solid ${theme.colors.inputBorder.main}`}
      borderRadius={'5px'}
      h="40px"
      fontSize={'14px'}
      value={input}
      w="500px"
      placeholder={placeholder}
      onChange={(e) => setInput(e.target.value)}
      onKeyDown={(e) => {
        if (e.key == 'Enter') onSubmit();
      }}
    />
  );
};

export default ConfigSearchBar;
