version: "3"
services:
  retail-ui:
    image: retail-business-console:ui
    build:
      context: .
    restart: always
    container_name: retail_ui
    env_file:
      - .env
    networks:
      - demo-network

networks:
  demo-network:
    external: true
