version: '3.5'
services:
  search-api:
    container_name: search-api
    build:
      context: .
      dockerfile: Dockerfile
    # image: search:base
    ports:
      - "8499:8499"
    volumes:
      - "./app:/server/app"
      - "./entrypoint.sh:/server/entrypoint.sh"
    env_file:
      - .env
    mem_limit: 8g
    privileged: true
    networks:
      - demo-network

networks:
  demo-network:
    external:
      name: demo-network
